Consumable[] =
{
/*	{Loot_MAGAZINE,		8,		ItemBandage},
	{Loot_MAGAZINE,		4,		ItemHeatPack},
	{Loot_MAGAZINE,		3,		ItemPainkiller},
	{Loot_MAGAZINE,		3,		ItemAntibacterialWipe},*/
	
	{Loot_MAGAZINE,		3,		ItemWaterBottleUnfilled}, //TODO: replace with canteen to better fit Epoch lootPosSmall
	{Loot_MAGAZINE,		8,		ItemWaterBottleSafe},
	{Loot_MAGAZINE,		3,		ItemWaterBottle},
	{Loot_MAGAZINE,		3,		ItemHeatPack},
	
	{Loot_MAGAZINE,		8,		ItemSodaCoke},
	{Loot_MAGAZINE,		8,		ItemSodaPepsi},
	{Loot_MAGAZINE,		1,		ItemSodaMdew},
	{Loot_MAGAZINE,		1,		ItemSodaRbull},
	{Loot_MAGAZINE,		1,		ItemSodaOrangeSherbet},

	{Loot_MAGAZINE,		8,		ItemSodaMtngreen},
	{Loot_MAGAZINE,		8,		ItemSodaR4z0r},
	{Loot_MAGAZINE,		8,		ItemSodaClays},
	{Loot_MAGAZINE,		8,		ItemSodaSmasht},
	{Loot_MAGAZINE,		8,		ItemSodaDrwaste},
	{Loot_MAGAZINE,		8,		ItemSodaFranka},
	{Loot_MAGAZINE,		8,		ItemSodaLemonade},
	{Loot_MAGAZINE,		8,		ItemSodaLirik},
	{Loot_MAGAZINE,		8,		ItemSodaLvg},
	{Loot_MAGAZINE,		8,		ItemSodaMzly},
	{Loot_MAGAZINE,		8,		ItemSodaPeppsy},
	{Loot_MAGAZINE,		8,		ItemSodaRabbit},
	{Loot_MAGAZINE,		8,		ItemSodaSacrite},
	{Loot_MAGAZINE,		8,		ItemSodaRocketFuel},
	{Loot_MAGAZINE,		8,		ItemSodaGrapeDrink},
	{Loot_MAGAZINE,		8,		ItemSherbet},
	
	{Loot_MAGAZINE,		8,		FoodPistachio},
	{Loot_MAGAZINE,		8,		FoodNutmix},
	{Loot_MAGAZINE,		8,		FoodChipsSulahoops},
	{Loot_MAGAZINE,		8,		FoodChipsMysticales},
	{Loot_MAGAZINE,		8,		FoodChipsChocolate},
	{Loot_MAGAZINE,		8,		FoodCandyChubby},
	{Loot_MAGAZINE,		8,		FoodCandyAnders},
	{Loot_MAGAZINE,		8,		FoodCandyLegacys},
	{Loot_MAGAZINE,		8,		FoodCandyMintception},
	{Loot_MAGAZINE,		8,		FoodCakeCremeCakeClean},
	
	{Loot_MAGAZINE,		8,		FoodCanBeef},
	{Loot_MAGAZINE,		8,		FoodCanPotatoes},
	{Loot_MAGAZINE,		8,		FoodCanGriff},
	{Loot_MAGAZINE,		8,		FoodCanBadguy},
	{Loot_MAGAZINE,		8,		FoodCanBoneboy},
	{Loot_MAGAZINE,		8,		FoodCanCorn},
	{Loot_MAGAZINE,		8,		FoodCanCurgon},
	{Loot_MAGAZINE,		8,		FoodCanDemon},
	{Loot_MAGAZINE,		8,		FoodCanFraggleos},
	{Loot_MAGAZINE,		8,		FoodCanHerpy},
	{Loot_MAGAZINE,		8,		FoodCanDerpy},
	{Loot_MAGAZINE,		8,		FoodCanOrlok},
	{Loot_MAGAZINE,		8,		FoodCanPowell},
	{Loot_MAGAZINE,		8,		FoodCanTylers},
	
	{Loot_MAGAZINE,		4,		FoodCanUnlabeled},
	{Loot_MAGAZINE,		8,		FoodCanBakedBeans},
	{Loot_MAGAZINE,		8,		FoodCanSardines},
	{Loot_MAGAZINE,		8,		FoodCanFrankBeans},
	{Loot_MAGAZINE,		8,		FoodCanPasta},
	{Loot_MAGAZINE,		8,		FoodBioMeat},
	
	{Loot_MAGAZINE,		5,		FoodCanRusUnlabeled},
	{Loot_MAGAZINE,		8,		FoodCanRusStew},
	{Loot_MAGAZINE,		8,		FoodCanRusPork},
	{Loot_MAGAZINE,		8,		FoodCanRusPeas},
	{Loot_MAGAZINE,		8,		FoodCanRusMilk},
	{Loot_MAGAZINE,		8,		FoodCanRusCorn}
};